[build]
  # Build command
  command = "chmod +x gradlew && ./gradlew html:dist"
  
  # Directory that contains the built website
  publish = "html/build/dist"

[build.environment]
  # Java version for build
  JAVA_VERSION = "17"

[[headers]]
  # Apply these headers to all files
  for = "/*"
  [headers.values]
    # Enable compression
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    
[[headers]]
  # Apply these headers to static assets
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    
[[headers]]
  # Apply these headers to the HTML files
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
